//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_Intakes_DataPumpNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_element_options
    {
        public int element_id { get; set; }
        public int option_id { get; set; }
        public string option { get; set; }
    }
}
