//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_Intakes_DataPumpNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class ap_form_12828_RAW
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string ip_address { get; set; }
        public string status { get; set; }
        public string element_1_1 { get; set; }
        public string element_1_2 { get; set; }
        public string element_2 { get; set; }
        public string element_43 { get; set; }
        public string element_44 { get; set; }
        public string element_41 { get; set; }
        public string element_3_1 { get; set; }
        public string element_3_2 { get; set; }
        public string element_3_3 { get; set; }
        public string element_3_4 { get; set; }
        public string element_3_5 { get; set; }
        public string element_3_6 { get; set; }
        public string element_19_1 { get; set; }
        public string element_19_2 { get; set; }
        public string element_19_3 { get; set; }
        public string element_19_4 { get; set; }
        public string element_19_5 { get; set; }
        public string element_19_6 { get; set; }
        public string element_32 { get; set; }
        public string element_49 { get; set; }
        public string element_50 { get; set; }
        public string element_51 { get; set; }
        public string element_52 { get; set; }
        public string element_5_1 { get; set; }
        public string element_5_2 { get; set; }
        public string element_6_1 { get; set; }
        public string element_6_2 { get; set; }
        public string element_6_3 { get; set; }
        public string element_6_4 { get; set; }
        public string element_6_5 { get; set; }
        public string element_6_6 { get; set; }
        public string element_7 { get; set; }
        public string element_9 { get; set; }
        public string element_20 { get; set; }
        public string element_12_1 { get; set; }
        public string element_12_2 { get; set; }
        public string element_13_1 { get; set; }
        public string element_13_2 { get; set; }
        public string element_13_3 { get; set; }
        public string element_13_4 { get; set; }
        public string element_13_5 { get; set; }
        public string element_13_6 { get; set; }
        public string element_16 { get; set; }
        public string element_21 { get; set; }
        public string element_22 { get; set; }
        public string element_25_1 { get; set; }
        public string element_25_2 { get; set; }
        public string element_26_1 { get; set; }
        public string element_26_2 { get; set; }
        public string element_26_3 { get; set; }
        public string element_26_4 { get; set; }
        public string element_26_5 { get; set; }
        public string element_26_6 { get; set; }
        public string element_14 { get; set; }
        public string element_27 { get; set; }
        public string element_24 { get; set; }
        public string element_23 { get; set; }
        public string element_70_1 { get; set; }
        public string element_70_2 { get; set; }
        public string element_73_1 { get; set; }
        public string element_73_2 { get; set; }
        public string element_73_3 { get; set; }
        public string element_73_4 { get; set; }
        public string element_73_5 { get; set; }
        public string element_73_6 { get; set; }
        public string element_76 { get; set; }
        public string element_79 { get; set; }
        public string element_82 { get; set; }
        public string element_85 { get; set; }
        public string element_69_1 { get; set; }
        public string element_69_2 { get; set; }
        public string element_72_1 { get; set; }
        public string element_72_2 { get; set; }
        public string element_72_3 { get; set; }
        public string element_72_4 { get; set; }
        public string element_72_5 { get; set; }
        public string element_72_6 { get; set; }
        public string element_75 { get; set; }
        public string element_78 { get; set; }
        public string element_81 { get; set; }
        public string element_84 { get; set; }
        public string element_68_1 { get; set; }
        public string element_68_2 { get; set; }
        public string element_71_1 { get; set; }
        public string element_71_2 { get; set; }
        public string element_71_3 { get; set; }
        public string element_71_4 { get; set; }
        public string element_71_5 { get; set; }
        public string element_71_6 { get; set; }
        public string element_74 { get; set; }
        public string element_77 { get; set; }
        public string element_83 { get; set; }
        public string element_80 { get; set; }
        public string element_33_11 { get; set; }
        public string element_33_12 { get; set; }
        public string element_33_13 { get; set; }
        public string element_33_14 { get; set; }
        public string element_33_15 { get; set; }
        public string element_33_16 { get; set; }
        public string element_33_17 { get; set; }
        public string element_33_18 { get; set; }
        public string element_33_19 { get; set; }
        public string element_33_20 { get; set; }
        public string element_33_21 { get; set; }
        public string element_33_22 { get; set; }
        public string element_33_other { get; set; }
        public string element_67 { get; set; }
        public string element_30 { get; set; }
        public string element_42 { get; set; }
        public string element_34 { get; set; }
    }
}
