//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_Intakes_DataPumpNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SLS_Intakes_DataPumpEntities : DbContext
    {
        public SLS_Intakes_DataPumpEntities()
            : base("name=SLS_Intakes_DataPumpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ap_element_options> ap_element_options { get; set; }
        public virtual DbSet<ap_form_12828_ARCHIVE> ap_form_12828_ARCHIVE { get; set; }
        public virtual DbSet<ap_form_12828_RAW> ap_form_12828_RAW { get; set; }
    }
}
